# Generated by Django 4.2.15 on 2024-08-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Заголовок')),
                ('author', models.CharField(verbose_name='Автор')),
                ('genre', models.CharField(verbose_name='Жанр')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('description', models.CharField(verbose_name='Описание')),
            ],
        ),
    ]
