# Generated by Django 4.2.15 on 2024-08-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='average_rating',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
